In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

Data Preparation

In [2]:
df_dataset = pd.read_csv('/workspaces/ML-Zoomcamp-Homework/Diseases-Symptoms Dataset/dataset.csv')
df_symptom_severity = pd.read_csv('/workspaces/ML-Zoomcamp-Homework/Diseases-Symptoms Dataset/Symptom-severity.csv')

In [3]:
df_dataset.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_dataset.shape

(4920, 18)

In [5]:
df_dataset.columns

Index(['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4',
       'Symptom_5', 'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9',
       'Symptom_10', 'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14',
       'Symptom_15', 'Symptom_16', 'Symptom_17'],
      dtype='object')

In [6]:
df_dataset.dtypes

Disease       object
Symptom_1     object
Symptom_2     object
Symptom_3     object
Symptom_4     object
Symptom_5     object
Symptom_6     object
Symptom_7     object
Symptom_8     object
Symptom_9     object
Symptom_10    object
Symptom_11    object
Symptom_12    object
Symptom_13    object
Symptom_14    object
Symptom_15    object
Symptom_16    object
Symptom_17    object
dtype: object

Exploratory Data Analysis for Diseases-Symptoms

In [8]:
for col in df_dataset.columns: 
    print(col)
    print(df_dataset[col].unique()[:10])
    print(df_dataset[col].nunique())
    print()

Disease
['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma']
41

Symptom_1
['itching' ' skin_rash' ' continuous_sneezing' ' shivering'
 ' stomach_pain' ' acidity' ' vomiting' ' indigestion' ' muscle_wasting'
 ' patches_in_throat']
34

Symptom_2
[' skin_rash' ' nodal_skin_eruptions' ' shivering' ' chills' ' acidity'
 ' ulcers_on_tongue' ' vomiting' ' yellowish_skin' ' stomach_pain'
 ' loss_of_appetite']
48

Symptom_3
[' nodal_skin_eruptions' ' dischromic _patches' ' chills'
 ' watering_from_eyes' ' ulcers_on_tongue' ' vomiting' ' yellowish_skin'
 ' nausea' ' stomach_pain' ' burning_micturition']
54

Symptom_4
[' dischromic _patches' nan ' watering_from_eyes' ' vomiting' ' cough'
 ' nausea' ' loss_of_appetite' ' burning_micturition'
 ' spotting_ urination' ' passage_of_gases']
50

Symptom_5
[nan ' cough' ' chest_pain' ' loss_of_appetite' ' abdominal_pain'
 ' spotting_ urination' ' internal_itching' ' passage_of_gases'
 ' irregular_sugar_level' ' blurred_and_distorted_vision']
38

Symptom_6
[nan ' chest_pain' ' abdominal_pain' ' yellowing_of_eyes'
 ' internal_itching' ' blurred_and_distorted_vision' ' obesity'
 ' mucoid_sputum' ' stiff_neck' ' depression']
32

Symptom_7
[nan ' yellowing_of_eyes' ' obesity' ' excessive_hunger' ' depression'
 ' irritability' ' dark_urine' ' abdominal_pain' ' muscle_pain'
 ' diarrhoea']
26

Symptom_8
[nan ' excessive_hunger' ' increased_appetite' ' irritability'
 ' visual_disturbances' ' abdominal_pain' ' muscle_pain' ' mild_fever'
 ' swelled_lymph_nodes' ' nausea']
21

Symptom_9
[nan ' increased_appetite' ' polyuria' ' visual_disturbances'
 ' swelled_lymph_nodes' ' malaise' ' loss_of_appetite'
 ' pain_behind_the_eyes' ' toxic_look_(typhos)' ' diarrhoea']
22

Symptom_10
[nan ' polyuria' ' malaise' ' red_spots_over_body' ' pain_behind_the_eyes'
 ' back_pain' ' belly_pain' ' toxic_look_(typhos)' ' yellowing_of_eyes'
 ' muscle_pain']
21

Symptom_11
[nan ' red_spots_over_body' ' back_pain' ' malaise' ' belly_pain'
 ' muscle_pain' ' receiving_blood_transfusion'
 ' receiving_unsterile_injections' ' coma' ' acute_liver_failure']
18

Symptom_12
[nan ' muscle_pain' ' malaise' ' receiving_unsterile_injections'
 ' stomach_bleeding' ' coma' ' swelled_lymph_nodes' ' sinus_pressure'
 ' runny_nose' ' irritability']
11

Symptom_13
[nan ' red_spots_over_body' ' muscle_pain' ' stomach_bleeding' ' malaise'
 ' phlegm' ' runny_nose' ' congestion' ' abnormal_menstruation']
8

Symptom_14
[nan ' red_spots_over_body' ' phlegm' ' chest_pain' ' congestion']
4

Symptom_15
[nan ' chest_pain' ' blood_in_sputum' ' loss_of_smell']
3

Symptom_16
[nan ' blood_in_sputum' ' loss_of_smell' ' muscle_pain']
3

Symptom_17
[nan ' muscle_pain']
1

In [9]:
df_dataset.isnull()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True
4916,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
4917,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
4918,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True
4919,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True

In [10]:
df_dataset.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64